### ISSUE TITLE
Update Pet Tag Lookup Endpoint

### ISSUE THREAD

**Issue by mccarthyk** [Commbocc/hc-pet-tag-lookup#2]
- [x] Use Vite
- [x] resizable iframe
- [x] New [API Endpoint](https://app.hillsboroughcounty.org/PetTagSearch/api/Animals)
- [x] CI/CD GitHub Action
- [x] rename 'master' branch to 'main'

RE: https://www.hillsboroughcounty.org/en/residents/animals-and-pets/lost-and-found-pets/pet-tag-lookup

**Comment by JordanPisani** [comment]
rewrote project using vite with updated endpoint
